name 'webapp'
maintainer 'Tim Ahtirski'
maintainer_email 'tim@ahtirski.com'
license 'Apache 2.0'
description 'Installs/Configures webapp'
long_description 'Installs/Configures webapp'
version '0.1.0'

depends 'apt'
depends 'apache2'
depends 'mysql'
depends 'mysql2_chef_gem'
depends 'database'
